---
# tasks file for hoplacloud.docker

- name: Install latest version of dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common

- name: Add an apt key by id from a keyserver
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Repository focal
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes
  when: "'focal' in ansible_distribution_release"

- name: Ensure docker is installed
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Ensure docker-compose is installed
  apt:
    name: docker-compose

- name: Start  docker
  service:
    name: docker
    state: started
    enabled: yes

#- name: Ensure docker is running
#  docker_ping:
#  register: result
#  retries: 5
#  delay: 10
#  until: result.ping == 'pong'
